### ISSUE TITLE
Test dataset - OrthoMosaic output

### ISSUE THREAD

**Issue by marleyshan21** [laxnpander/OpenREALM#101]
Hi!

I was running the test dataset in 2D mapping with visual SLAM mode. 
I am seeing disparity in the results when compared to the video of OpenRealm.
![Screenshot from 2024-01-23 13-36-25](https://github.com/laxnpander/OpenREALM/assets/43117628/a641ca74-b321-4a11-95a9-cb0ab15bcc9a)
![Screenshot from 2024-01-23 13-38-21](https://github.com/laxnpander/OpenREALM/assets/43117628/c50ef58b-826e-4135-94e9-5185e10ec839)

I tried playing around primarily with nrof_features for the orb extractor and ground sampling distance.
What are the other main parameters that i need to tune? 
The images are for the default parameters that are present in the repo. 

@laxnpander

**Comment by laxnpander** [comment]
@marleyshan21 I'd rather load the output gtiff into apps like QGIS and check there. I am pretty sure some of the static transformers is publishing a wrong transformation or the satellite map uses a wrong transformation. The output data is unaffected by that, just a visualisation issue. Not sure if I find the time fix it.

**Comment by marleyshan21** [comment]
Ah okay ✌️!
I will try it out on QGIS.

Also, I will work on checking this static transform part. 
If you could guide me on where this static transform part exists in the code, i could check it out and try fixing it. 

Lemme know!

**Comment by marleyshan21** [comment]
I tried it with QGIS. The results are a lot better with slight differences w.r.t the ground truth
![Screenshot from 2024-01-24 11-56-07](https://github.com/laxnpander/OpenREALM/assets/43117628/f7b1a364-ce60-4e13-bb45-0d19d0b793e1)

![Screenshot from 2024-01-24 11-56-40](https://github.com/laxnpander/OpenREALM/assets/43117628/6ef402c9-170f-4fdd-ad4a-fde0007173b2)

I will checkout the code regarding this static transform part.
I could use your help in zeroing in on the file and function where these things happen.

**Comment by laxnpander** [comment]
If it's on OpenREALM side it is somewhere here:

https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/master/realm_ros/src/realm_ros_lib/stage_node.cpp

Have you tried the rviz_satellite fork from my GitHub? 

https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/master/realm_ros/src/realm_ros_lib/stage_node.cpp

I think I remember there was an issue with some frames being redefined that caused the misalignment.

**Comment by marleyshan21** [comment]
Using your fork of rviz_satellite solved it!
https://github.com/laxnpander/rviz_satellite

![Screenshot from 2024-01-25 09-45-16](https://github.com/laxnpander/OpenREALM/assets/43117628/0329c940-48d2-4dfb-8b2f-f820535d4805)


Based on your commit, it looks like an issue with the frame being lookedup to determine the transformation. Your fork uses the one needed by OpenRealm

Thanks for the help @laxnpander!

**Comment by laxnpander** [comment]
Sure, glad I could help.
