### ISSUE TITLE
The performance is not very satisfactory when using my own dataset.

### ISSUE THREAD

**Issue by Aishop119** [laxnpander/OpenREALM#102]
Hello, thank you very much for your outstanding contribution. I would like to ask, after adding latitude, longitude, and altitude information exiv2 tags to the images in my own dataset, and modifying the camera parameter configuration in calib.yaml, what other modifications do I need to make? 
Currently, I have only made these changes, but the results are not satisfactory. 
I am looking forward to your reply, thank you.

**Comment by laxnpander** [comment]
Depends on a lot of factors, such as quality of camera, overlap etc. pp. What drone do you use? What resolution? What frame rate?

**Comment by Aishop119** [comment]
I use the DJI Phantom 4 RTK with a frame rate set at 10fps and a frame size of 1920x1080. The front and rear overlap rate is 0.995, and the left and right overlap rate is 0.78. The shooting is conducted on a farm.
![img-0034](https://github.com/laxnpander/OpenREALM/assets/95087718/7dbc3d7c-7dba-4eb5-a7f2-59751a634588)

**Comment by Aishop119** [comment]
And the mosaic result as this
![d54127ca4fecde8f33a49a3504c7aa0](https://github.com/laxnpander/OpenREALM/assets/95087718/47eaf6d5-c3ee-484d-8267-572399d52abc)
![11643499c104c2de852ab7870ec7f10](https://github.com/laxnpander/OpenREALM/assets/95087718/30ad6368-bc22-418f-a032-f44374bb470d)

**Comment by laxnpander** [comment]
@Aishop119 Looks like tracking was not really good. I've seen similar behaviour in other datasets and usually this happens when the camera calibration is not good. How did you calibrate your setup? Do you think you can improve it?

**Comment by laxnpander** [comment]
Closed until reopen.

**Comment by OrduVictor** [comment]
@Aishop119 Hey, were you able to successfully run the pipeline with your custom dataset?. If yes, would it be possible for you to share this with me?.
