### ISSUE TITLE
No tracking on my dataset

### ISSUE THREAD

**Issue by lyy-1997** [laxnpander/OpenREALM#105]
Thanks a lot for your work.
I have successfully run gnss,noreo and reco using both the provided test data set and my own (**1014x760 resolution, 126m flight altitude**). However, when I used a dataset with a resolution of **6144x4096 and a flight altitude of 171m**, I was never able to complete 3D mapping.Even if the camera parameters are perfectly correct, there are still a few things that are strange.
1.No tracking has been displayed since the beginning.
2.Even though the image has obvious features, there are almost no feature points in rviz.
Since I have previously successfully run the data set of 1014x760 resolution (the resolution is similar to the test data set provided), I am guessing that the resolution of 6144x4096 May be causing the problem? Or was it flight altitude?If so, how should I configure it correctly?THANKS!
By the way, I only changed the camera parameter configuration in profile/*/camera/calib.yaml, and the resolution Settings were consistent with the image size.

**Here is the output file.**
[output.txt](https://github.com/laxnpander/OpenREALM/files/14381479/output.txt)

![noFeaturePoints](https://github.com/laxnpander/OpenREALM/assets/59129828/aa1a1e8e-2d57-422e-8940-b46829ae3fd1)
![output](https://github.com/laxnpander/OpenREALM/assets/59129828/0fc01339-7a56-465b-9aa8-0b45dedeea43)

**Comment by laxnpander** [comment]
@lyy-1997 Hey, welcome to the dark arts of tuning OpenREALM. I am pretty sure your image resolution is way too high.I'd start with significantly smaller images. You can resize them automatically using the configs in the respective profile, e.g.

https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/65a86d465b5ba0b5256f5c8f1bb8090ec3a027f8/realm_ros/profiles/alexa_reco/pose_estimation/method/orb_slam3_settings.yaml#L6

So set resizing to 0.2 and see if the results improve. You can also increase nrof features if you have the processing power to back it up.

**Comment by lyy-1997** [comment]
Thanks for your reply.
I've switched to a lower resolution dataset and got the desired results. So I think it's the resolution of the dataset.
When I set resizing to 0.2, do I need to adjust the camera parameters in calib.yam for the dataset with a high resolution? If so, how should I set the camera parameters?I guese, keep other parameters unchanged, only adjust the width and height of the camera parameters to 0.2 times the original?
By the way, does the current version successfully support ORBSLAM3, because I saw that you mentioned ORBSLAM3 in your reply?

**Comment by laxnpander** [comment]
@lyy-1997 Ah jeah, ORBSLAM3 was tested by me, but it is not the default in the repo atm. OpenVSLAM was performing better in most cases. The camera parameters are scaled automatically according to the resize value you set. So you don't have to edit them manually.

**Comment by laxnpander** [comment]
Reopen if issues persists.

**Comment by gityeezy** [comment]
你好 @lyy-1997 ，你自己录制的数据集是怎么做的，你的图片制作好后，除了照片分辨率外，代码中还需要修改哪些内容？

**Comment by OrduVictor** [comment]
@lyy-1997 Hey, I see you were able to successfully run the pipeline with your custom dataset. Would it be possible for you to share this with me?. My dataset was obtained from a DJI drone.
My custom dataset specs are:
1. image resolution of 4032x3024
2. fps of about 0.1667 (a 6 secs interval between images)
3. at an altitude of 186m, GPS coordinates were obtained in RTK mode
