### ISSUE TITLE
why not orthorectification?

### ISSUE THREAD

**Issue by Sandeldeng** [laxnpander/OpenREALM#11]
I have an idea.I think if it would be OK that not densify the depthmap, and densification after orthorectification.Because I think the point with depth in depthmap is just 1000,Interplation may cause many error, cause the later stage.

**Comment by immuhammadadil** [comment]
HI,
Was you able to successfully test the OpenREALM?

**Comment by laxnpander** [comment]
I don’t quite understand what you want to do? Densification is necessary to perform orthorectification. It reconstructs the 3D scene and only afterwards you can correct it?
