### ISSUE TITLE
Question about mapping launch files

### ISSUE THREAD

**Issue by homayoonh79** [laxnpander/OpenREALM#110]
I need 2.5D mapping with visual SLAM. 
i use "roslaunch realm_ros alexa_gnss.launch" for GNSS mapping and can see mosaicing in Rviz.
also when using "roslaunch realm_ros alexa_noreco.launch" everything is ok and can see mosaicing in Rviz.
but i need 2.5D mapping. when i use "roslaunch realm_ros alexa_reco.launch" nothing show in Rviz. why?
@ZackStone233

**Comment by ZackStone233** [comment]
Sorry for the late reply.This usually occurs due to an issue with the installation. If you are using the PSL method, please make sure that the OpenCV version is correct and that the contrib package is installed.

**Comment by laxnpander** [comment]
This is not enough info to help you. Reopen if you have more to provide.
