### ISSUE TITLE
undefined reference to `openvslam::system::get_tracker_state() const

### ISSUE THREAD

**Issue by Yangchengshuai** [laxnpander/OpenREALM#111]
when catkin_make error:
OpenREALM/catkin_ws/devel/lib/librealm_ros.so: undefined reference to `openvslam::system::get_tracker_state() const'

**Comment by laxnpander** [comment]
I use a slightly customised version of openvslam, which can be found here: https://github.com/laxnpander/openvslam

Reopen if problems persist.
