### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by immuhammadadil** [laxnpander/OpenREALM#12]
Its a request to kindly upload the docker image of openREALM. It would be a great help to the community

**Comment by laxnpander** [comment]
@immuhammadadil: We will think about it. End of 2019 I am back in Germany and further development is taken out. Until then I am afraid you have to use what’s there :)

**Comment by laxnpander** [comment]
@immuhammadadil: FYI: There is a docker image now! Feel free to check it out.
