### ISSUE TITLE
What is the frame rate recommended to capture custom dataset?

### ISSUE THREAD

**Issue by immuhammadadil** [laxnpander/OpenREALM#13]

**Comment by laxnpander** [comment]
We captured with 10 FPS which was working pretty well. The more the better, but don’t forget that it is a compromise between resolution/FPS/data size. Higher frame rates tend to be more stable for the visual SLAM, but they were result in less accurate maps. So if you ask me: 10 FPS is good!

**Comment by immuhammadadil** [comment]
Alrigh Thanks.
