### ISSUE TITLE
Didn't find alexa_noreco.launch.

### ISSUE THREAD

**Issue by xycai-pku** [laxnpander/OpenREALM#44]
Thanks for your nice work,
I didn't find alexa_noreco.launch in in OpenREALM_ROS1_Bridge/realm_ros/launch.

And when I run roslaunch realm_ros alexa_reco.launch, I meet errr here:

[realm_densification-3] process has died [pid 114470, exit code -6, cmd /home/xycai/catkin_ws/devel/lib/realm_ros/realm_stage_node __name:=realm_densification __log:=/home/xycai/.ros/log/7c529264-8117-11eb-b5bf-000c29e630fd/realm_densification-3.log].
log file: /home/xycai/.ros/log/7c529264-8117-11eb-b5bf-000c29e630fd/realm_densification-3*.log

[ERROR] [1615323012.719473611]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: According to the loaded plugin descriptions the class rviz_plugins/AerialMapDisplay with base class type rviz::Display does not exist. Declared types are  realm_rviz_plugin/GroundImage rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/WrenchStamped

**Comment by laxnpander** [comment]
@xycai-pku: Should be fixed now. There was a missing launch file + profile. Have a look at https://github.com/laxnpander/OpenREALM_ROS1_Bridge and pull the latest commit.

**Comment by xycai-pku** [comment]
Thank you so much！
