### ISSUE TITLE
AutoPtr seems to be deprecated in Exiv2

### ISSUE THREAD

**Issue by rexsham** [laxnpander/OpenREALM#5]
exif_import.cpp line 33

Exiv2::Image::AutoPtr exif_img = Exiv2::ImageFactory::open(filepath);

catkin will fail in building if I use latest version of Exiv2-0.27.1
I changed AutoPtr to UniquePtr and it can build correctly

Exiv2::Image::UniquePtr exif_img = Exiv2::ImageFactory::open(filepath);

**Comment by laxnpander** [comment]
@rexsham Good call! I am gonna investigate on that!

**Comment by laxnpander** [comment]
@rexsham: Looks like the unique pointer is a new concept in Exiv2. So not compatible with the older versions. I will add a hint to the readme and wait with the fix for the Ubuntu 18 update.
