### ISSUE TITLE
links to target "FLANN::FLANN" but the target was  not found.

### ISSUE THREAD

**Issue by Mengke-Yuan** [laxnpander/OpenREALM#55]
Hi Laxnpander,

        I got error in building OpenREALM_ROS1_Bridge with Ubuntu16.04 and ROS Kinetic. The first 'catkin_make -DCMAKE_BUILD_TYPE=Release' gives :
[catkin_make_1st.txt](https://github.com/laxnpander/OpenREALM/files/6330329/catkin_make_1st.txt)
and the second 'catkin_make -DCMAKE_BUILD_TYPE=Release' gives:
[catkin_make_2nd.txt](https://github.com/laxnpander/OpenREALM/files/6330330/catkin_make_2nd.txt)
It seems relative to 'FLANN'. I will be appreciated if you can give some hints. Regards!

**Comment by laxnpander** [comment]
@Mengke-Yuan: Hey, what OS are you using? Ubuntu 20.04? There are a couple of these issues, also Vtk is causing some headache on 20.04 when compiled with PCL. I will have a look into it.

**Comment by Mengke-Yuan** [comment]
> 
> 
> @Mengke-Yuan: Hey, what OS are you using? Ubuntu 20.04? There are a couple of these issues, also Vtk is causing some headache on 20.04 when compiled with PCL. I will have a look into it.

I am using Ubuntu16.04 and Kinetic. Thanks!

**Comment by laxnpander** [comment]
@Mengke-Yuan: A quick fix should be to add `find_package(FLANN REQUIRED)` in the CMakeLists somewhere around here: https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/a364858df04debf7e5eceb22c79caa45fd49a0a0/realm_ros/CMakeLists.txt#L68

**Comment by Mengke-Yuan** [comment]
Adding `find_package(FLANN REQUIRED)` worked. But new errors appears as shown in:
[log.txt](https://github.com/laxnpander/OpenREALM/files/6339786/log.txt)
Representative errors are :
1. /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options. 
But I see the cmake setting at https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/a364858df04debf7e5eceb22c79caa45fd49a0a0/CMakeLists.txt#L51
2. usr/local/include/OpenREALM/realm_core/cv_grid_map.h:35:11: error: expected nested-name-specifier before ‘Ptr’
     using Ptr = std::shared_ptr<CvGridMap>;
           ^
/usr/local/include/OpenREALM/realm_core/cv_grid_map.h:36:11: error: expected nested-name-specifier before ‘ConstPtr’
     using ConstPtr = std::shared_ptr<const CvGridMap>;
           ^
/usr/local/include/OpenREALM/realm_core/cv_grid_map.h:38:11: error: expected nested-name-specifier before ‘Overlap’
     using Overlap = std::pair<CvGridMap::Ptr, CvGridMap::Ptr>;
3.error: ‘cv::InterpolationFlags’ is not a class or namespace
     void add(const std::string &layer_name, const cv::Mat &layer_data, int interpolation = cv::InterpolationFlags::INTER_LINEAR);
This may relate to OpenCV version?

Are there any dependences missing in my configuration? Thanks!

**Comment by laxnpander** [comment]
@Mengke-Yuan: Hmm, this is weird. First time I see this error! This is not on ARM, is it? Error 2) might be related to the c++11 standard missing. So I'd try to fix the first issue and then see how it goes. However, it is difficult to debug without having your same hardware. I assume your compiler is old or outdated. Also, can you check what cmake version you use (terminal: cmake --version)?

I also found this which you could try: https://stackoverflow.com/questions/10851247/how-do-i-activate-c-11-in-cmake

**Comment by Mengke-Yuan** [comment]
@laxnpander : My cmake version is 3.16.6 with an Intel CPU.

**Comment by laxnpander** [comment]
@Mengke-Yuan: Hmmm, can you try to set the c++ standard to 14 for the ROS bridge? The main library is using c++14 https://github.com/laxnpander/OpenREALM/blob/465ecc8a68a55dd7fee956af01b56169ea6db231/CMakeLists.txt#L118
I have not experienced an issue with it yet, but maybe there is with your compiler version.

**Comment by Mengke-Yuan** [comment]
@laxnpander : The compiler outputs seem unchanged after using c++14.

**Comment by laxnpander** [comment]
@Mengke-Yuan: Alright, there is not much I can do unfortunately. You will have to find out what causes this problem on your specific system. Alternatively you can try to use the docker instead. Not sure if this is suitable for your application?

**Comment by Mengke-Yuan** [comment]
@laxnpander: Thanks for your help.

**Comment by laxnpander** [comment]
@Mengke-Yuan Sure, you are welcome

**Comment by Ahmad-Drak** [comment]
@Mengke-Yuan did you manage to solve this after all?

**Comment by howz-chen** [comment]
When I build the env based on Ubuntu20.04, I also meet this issue and others.

Include:
**1. vtk related issue, such as** 

 -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- The imported target "vtkParseOGLExt" references the file
   "/usr/bin/vtkParseOGLExt-7.1"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

**When I find solve method, there exist a method that** 
1)  "sudo ln -s /usr/lib/python2.7/dist-packages/vtk/libvtkRenderingPythonTkWidgets.x86_64-linux-gnu.so /usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
2)   sudo ln -s /usr/bin/vtk6 /usr/bin/vtk 

While on Ubuntu20.04, there is no libvtkRenderingPythonTkWidgets.x86_64-linux-gnu.so at /usr/lib/python2.7/dist-packages/vtk/
and installed vtk is default vtk7

**2. Issue about  "links to target FLANN::FLANN but the target was not found"**
    I install the flann with apt-get and also download flann from github, and add "find_package(FLANN REQUIRED)" at CMakeLists.txt, but it still raise this error, and the same error exist with "boost".

So, if this repo support Ubuntu20.04 now? 
@laxnpander  Look forward to your reply, thanks~

**Comment by laxnpander** [comment]
It definitely builds on Ubuntu 20.04. Under some configurations (installed libraries, library versions) errors like yours occur. Currently, I have no time to fix this for everyone. So I am afraid you are on your own. 

One solution might be to build it without PCL, which is the root of a lot of trouble. I think there is a build flag for that. I’ll let you know when I find the time to look at it:

**Comment by howz-chen** [comment]
> It definitely builds on Ubuntu 20.04. Under some configurations (installed libraries, library versions) errors like yours occur. Currently, I have no time to fix this for everyone. So I am afraid you are on your own.
> 
> One solution might be to build it without PCL, which is the root of a lot of trouble. I think there is a build flag for that. I’ll let you know when I find the time to look at it:

Thanks for your quick reply, 

I change to use Ubuntu18.04 docker image based on arm64(NVIDIA Jetson AGX Orin), and follow the steps, and now can run test demo successfully.

**Comment by KanonWY** [comment]
@howz-chen hi,  Is there a solution in Ubuntu20?  I also encountered this problem!

**Comment by aurovoy** [comment]
this error may solved by locate a "findFLANN.cmake" file, copy the code to the CmakeList.txt
