### ISSUE TITLE
realm_pose_estimation-3 process has died 

### ISSUE THREAD

**Issue by yafenggithub** [laxnpander/OpenREALM#67]
I can run "roslaunch realm_ros alexa_gnss.launch " very well,but when run "roslaunch realm_ros alexa_noreco.launch "and "roslaunch realm_ros alexa_reco.launch ",I get the error "[realm_pose_estimation-3] process has died [pid 23631, exit code -9, cmd /home/ubuntu/catkin_ws/devel/lib/realm_ros/realm_stage_node __name:=realm_pose_estimation __log:=/home/ubuntu/.ros/log/51d3957e-1bae-11ec-afdd-3cf862d9f68e/realm_pose_estimation-3.log].
log file: /home/ubuntu/.ros/log/51d3957e-1bae-11ec-afdd-3cf862d9f68e/realm_pose_estimation-3*.log"   but I cannot find the log.Please help me. Thanks
I try it on Ubuntu18.04,try VMware  and WSL and PC,the error alway on,the all ouput message is:

... logging to /home/ubuntu/.ros/log/51d3957e-1bae-11ec-afdd-3cf862d9f68e/roslaunch-ubuntu-23606.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:43223/

SUMMARY
========

PARAMETERS
 * /realm_exiv2_grabber/config/id: ubuntu
 * /realm_exiv2_grabber/config/input: /media/ubuntu/DAT...
 * /realm_exiv2_grabber/config/profile: alexa_noreco
 * /realm_exiv2_grabber/config/rate: 10.0
 * /realm_mosaicing/config/id: ubuntu
 * /realm_mosaicing/config/profile: alexa_noreco
 * /realm_mosaicing/stage/type: mosaicing
 * /realm_mosaicing/topics/input/frame: /realm/ubuntu/ort...
 * /realm_ortho_rectification/config/id: ubuntu
 * /realm_ortho_rectification/config/profile: alexa_noreco
 * /realm_ortho_rectification/stage/type: ortho_rectification
 * /realm_ortho_rectification/topics/input/frame: /realm/ubuntu/sur...
 * /realm_ortho_rectification/topics/output: /realm/ubuntu/ort...
 * /realm_pose_estimation/config/id: ubuntu
 * /realm_pose_estimation/config/method: open_vslam
 * /realm_pose_estimation/config/profile: alexa_noreco
 * /realm_pose_estimation/stage/master: False
 * /realm_pose_estimation/stage/type: pose_estimation
 * /realm_pose_estimation/topics/input/frame: /realm/ubuntu/input
 * /realm_pose_estimation/topics/output: /realm/ubuntu/pos...
 * /realm_surface_generation/config/id: ubuntu
 * /realm_surface_generation/config/profile: alexa_noreco
 * /realm_surface_generation/stage/type: surface_generation
 * /realm_surface_generation/topics/input/frame: /realm/ubuntu/pos...
 * /realm_surface_generation/topics/output: /realm/ubuntu/sur...
 * /rosdistro: melodic
 * /rosversion: 1.14.11

NODES
  /
    realm_exiv2_grabber (realm_ros/realm_exiv2_grabber)
    realm_mosaicing (realm_ros/realm_stage_node)
    realm_ortho_rectification (realm_ros/realm_stage_node)
    realm_pose_estimation (realm_ros/realm_stage_node)
    realm_surface_generation (realm_ros/realm_stage_node)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [23616]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 51d3957e-1bae-11ec-afdd-3cf862d9f68e
process[rosout-1]: started with pid [23627]
started core service [/rosout]
process[realm_exiv2_grabber-2]: started with pid [23630]
process[realm_pose_estimation-3]: started with pid [23631]
process[realm_surface_generation-4]: started with pid [23632]
process[realm_ortho_rectification-5]: started with pid [23637]
process[realm_mosaicing-6]: started with pid [23638]
process[rviz-7]: started with pid [23639]
[ INFO] [1632319606.205668389]: STAGE_NODE [pose_estimation]: Loading stage settings from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/pose_estimation/stage_settings.yaml
[ INFO] [1632319606.206835631]: STAGE_NODE [pose_estimation]: Detected stage type: 'pose_estimation'
[ INFO] [1632319606.211654002]: STAGE_NODE [pose_estimation]: : Loading camera from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1632319606.211835892]: STAGE_NODE [pose_estimation]: : Detected camera model: 'pinhole'
[ INFO] [1632319606.211865753]: STAGE_NODE [pose_estimation]: : Loading vslam settings from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/pose_estimation/method/open_vslam_settings.yaml
[ INFO] [1632319606.211980372]: STAGE_NODE [pose_estimation]: : Detected vslam type: 'OPEN_VSLAM'
2021-09-22 14:06:46.212 (   0.030s) [        1A710680]    pose_estimation.cpp:40       0| Stage [pose_estimation]: Created Stage with Settings:

	<Param>[save_keyframes_full]: 0
	<Param>[save_frames]: 0
	<Param>[save_trajectory_gnss]: 1
	<Param>[save_trajectory_visual]: 1
	<Param>[overlap_max_fallback]: 95
	<Param>[use_vslam]: 1
	<Param>[path_output]: 
	<Param>[queue_size]: 10
	<Param>[min_nrof_frames_georef]: 5
	<Param>[use_imu]: 0
	<Param>[type]: pose_estimation
	<Param>[set_all_frames_keyframes]: 0
	<Param>[init_lost_frames_reset_count]: 15
	<Param>[fallback_strategy]: 1
	<Param>[update_georef]: 0
	<Param>[save_keyframes]: 0
	<Param>[log_to_file]: 1
	<Param>[do_delay_keyframes]: 1
	<Param>[suppress_outdated_pose_pub]: 0
	<Param>[use_initial_guess]: 0
	<Param>[th_error_georef]: 1
	<Param>[overlap_max]: 100
[2021-09-22 14:06:46.212] [info] config file loaded: 
[2021-09-22 14:06:46.215] [info] 
  ___               __   _____ _      _   __  __ 
 / _ \ _ __  ___ _ _\ \ / / __| |    /_\ |  \/  |
| (_) | '_ \/ -_) ' \\ V /\__ \ |__ / _ \| |\/| |
 \___/| .__/\___|_||_|\_/ |___/____/_/ \_\_|  |_|
      |_|                                        

Copyright (C) 2019,
National Institute of Advanced Industrial Science and Technology (AIST)
All rights reserved.

This is free software,
and you are welcome to redistribute it under certain conditions.
See the LICENSE file.

Camera:
  fx: 725.4394416
  fy: 726.3970548
  cx: 366.1941516
  cy: 310.1503962
  k1: -0.198806
  k2: 0.122544
  p1: -0.000221
  p2: -0.000877
  k3: 0
  name: cam
  model: perspective
  color_order: RGB
  fps: 10
  cols: 736
  rows: 615
  setup: monocular
Feature:
  max_num_keypoints: 2000
  ini_max_num_keypoints: 4000
  num_levels: 12
  scale_factor: 1.1
  ini_fast_threshold: 20
  min_fast_threshold: 5
Mapping:
  baseline_dist_thr_ratio: 0.02

[2021-09-22 14:06:46.215] [info] loading ORB vocabulary: /home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/pose_estimation/method/open_vslam/orb_vocab.fbow
[ INFO] [1632319606.250372020]: STAGE_NODE [surface_generation]: Loading stage settings from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/surface_generation/stage_settings.yaml
[ INFO] [1632319606.252467341]: STAGE_NODE [surface_generation]: Detected stage type: 'surface_generation'
[ INFO] [1632319606.259459615]: STAGE_NODE [surface_generation]: : Loading camera from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1632319606.259607720]: STAGE_NODE [surface_generation]: : Detected camera model: 'pinhole'
[ INFO] [1632319606.262160130]: STAGE_NODE [surface_generation]: Started stage node successfully!
2021-09-22 14:06:46.262 (   0.031s) [Stage [surface_g] worker_thread_base.cpp:43       0| Thread 'Stage [surface_generation]' starting loop...
[ INFO] [1632319606.282169342]: STAGE_NODE [mosaicing]: Loading stage settings from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/mosaicing/stage_settings.yaml
[ INFO] [1632319606.283451126]: STAGE_NODE [ortho_rectification]: Loading stage settings from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/ortho_rectification/stage_settings.yaml
[ INFO] [1632319606.283987868]: STAGE_NODE [mosaicing]: Detected stage type: 'mosaicing'
[ INFO] [1632319606.284514563]: STAGE_NODE [ortho_rectification]: Detected stage type: 'ortho_rectification'
[ INFO] [1632319606.294599723]: STAGE_NODE [mosaicing]: : Loading camera from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1632319606.294814405]: STAGE_NODE [mosaicing]: : Detected camera model: 'pinhole'
Stage [mosaicing]: Created Stage with Settings: 
[ INFO] [1632319606.294915520]: Exiv2 Grabber Node [Ankommen]: Successfully loaded camera: 
	cx = 610.324
	<Param>[save_num_obs_all]: 0
	cy = 516.917
	<Param>[save_num_obs_one]: 1
	fx = 1209.07
	<Param>[save_elevation_mesh_one]: 0
	fy = 1210.66
	<Param>[save_elevation_obs_angle_all]: 0
	k1 = -0.198806
	<Param>[save_elevation_obs_angle_one]: 1
	k2 = 0.122544
	<Param>[save_elevation_var_all]: 0
	p1 = -0.000221
	<Param>[save_elevation_all]: 0
	p2 = -0.000877
	<Param>[th_elevation_variance]: 1
	<Param>[th_elevation_min_nobs]: 2
	<Param>[path_output]: 
	<Param>[save_dense_ply]: 1
	<Param>[queue_size]: 5
	<Param>[save_elevation_var_one]: 0
	<Param>[log_to_file]: 1
	<Param>[save_ortho_rgb_one]: 1
	<Param>[type]: mosaicing
	<Param>[publish_mesh_every_nth_kf]: 0
	<Param>[publish_mesh_at_finish]: 1
	<Param>[save_ortho_gtiff_one]: 1
	<Param>[split_gtiff_channels]: 0
	<Param>[save_elevation_one]: 1
	<Param>[save_ortho_gtiff_all]: 0
	<Param>[downsample_publish_mesh]: 0.5
	<Param>[save_valid]: 0
	<Param>[save_ortho_rgb_all]: 0
[ INFO] [1632319606.298371885]: STAGE_NODE [ortho_rectification]: : Loading camera from path:
	/home/ubuntu/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1632319606.298557012]: STAGE_NODE [ortho_rectification]: : Detected camera model: 'pinhole'
Stage [ortho_rectification]: Created Stage with Settings: 
	<Param>[save_elevation]: 0
	<Param>[save_ortho_gtiff]: 0
	<Param>[save_valid]: 0
	<Param>[save_elevation_angle]: 0
	<Param>[type]: ortho_rectification
	<Param>[save_ortho_rgb]: 0
	<Param>[log_to_file]: 1
	<Param>[publish_pointcloud]: 0
	<Param>[queue_size]: 5
	<Param>[path_output]: 
	<Param>[GSD]: 0.1
[ INFO] [1632319606.302635851]: STAGE_NODE [ortho_rectification]: Started stage node successfully!
2021-09-22 14:06:46.302 (   0.045s) [Stage [ortho_rec] worker_thread_base.cpp:43       0| Thread 'Stage [ortho_rectification]' starting loop...
[ INFO] [1632319606.303720143]: STAGE_NODE [mosaicing]: Started stage node successfully!
2021-09-22 14:06:46.303 (   0.047s) [Stage [mosaicing] worker_thread_base.cpp:43       0| Thread 'Stage [mosaicing]' starting loop...
[ INFO] [1632319606.510875165]: Scanning input image for provided meta tags...
[ INFO] [1632319606.528516735]: [FOUND]		'Exif.GPSInfo.GPSAltitude'
[ INFO] [1632319606.528578074]: [FOUND]		'Exif.GPSInfo.GPSLatitude'
[ INFO] [1632319606.528612604]: [FOUND]		'Exif.GPSInfo.GPSLatitudeRef'
[ INFO] [1632319606.528630793]: [FOUND]		'Exif.GPSInfo.GPSLongitude'
[ INFO] [1632319606.528658831]: [FOUND]		'Exif.GPSInfo.GPSLongitudeRef'
[ INFO] [1632319606.528691005]: [FOUND]		'Exif.Image.Model'
[ INFO] [1632319606.528705637]: [FOUND]		'Xmp.exif.REALM.Heading'
[ WARN] [1632319606.528721543]: [NOT FOUND]	'Xmp.exif.REALM.Timestamp'
[ INFO] [1632319606.528786692]: Image #0, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0000.jpg
[ INFO] [1632319606.772487546]: Image #1, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0001.jpg
[ INFO] [1632319607.003504440]: Image #2, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0002.jpg
[ INFO] [1632319607.261727303]: Image #3, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0003.jpg
[ INFO] [1632319607.595884132]: Image #4, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0004.jpg
[realm_pose_estimation-3] process has died [pid 23631, exit code -9, cmd /home/ubuntu/catkin_ws/devel/lib/realm_ros/realm_stage_node __name:=realm_pose_estimation __log:=/home/ubuntu/.ros/log/51d3957e-1bae-11ec-afdd-3cf862d9f68e/realm_pose_estimation-3.log].
log file: /home/ubuntu/.ros/log/51d3957e-1bae-11ec-afdd-3cf862d9f68e/realm_pose_estimation-3*.log
[ INFO] [1632319615.151640535]: Image #5, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0005.jpg
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:103      0| { Stage [surface_generation] statistics
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:104      0| .   Total frames: 0 
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:105      0| .   Processed frames: 0 
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:106      0| .   Bad frames: 0 
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:107      0| .   Dropped frames: 0 
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:108      0| .   Fps in: 0.00 
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:109      0| .   Fps out: 0.00 
2021-09-22 14:06:56.259 (  10.028s) [        ABFFF700]         stage_base.cpp:103      0| } 0.000 s: Stage [surface_generation] statistics
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:103      0| { Stage [mosaicing] statistics
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:104      0| .   Total frames: 0 
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:105      0| .   Processed frames: 0 
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:106      0| .   Bad frames: 0 
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:107      0| .   Dropped frames: 0 
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:108      0| .   Fps in: 0.00 
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:109      0| .   Fps out: 0.00 
2021-09-22 14:06:56.295 (  10.038s) [          C3C700]         stage_base.cpp:103      0| } 0.000 s: Stage [mosaicing] statistics
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:103      0| { Stage [ortho_rectification] statistics
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:104      0| .   Total frames: 0 
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:105      0| .   Processed frames: 0 
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:106      0| .   Bad frames: 0 
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:107      0| .   Dropped frames: 0 
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:108      0| .   Fps in: 0.00 
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:109      0| .   Fps out: 0.00 
2021-09-22 14:06:56.298 (  10.041s) [        93FFF700]         stage_base.cpp:103      0| } 0.000 s: Stage [ortho_rectification] statistics
[ INFO] [1632319616.340901759]: Image #6, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0006.jpg
[ INFO] [1632319616.576033998]: Image #7, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0007.jpg
[ INFO] [1632319616.782662306]: Image #8, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0008.jpg
[ INFO] [1632319617.016339571]: Image #9, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0009.jpg
[ INFO] [1632319617.205225696]: Image #10, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0010.jpg
[ INFO] [1632319617.459302860]: Image #11, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0011.jpg
[ INFO] [1632319617.657814070]: Image #12, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0012.jpg
[ INFO] [1632319617.877983860]: Image #13, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0013.jpg
[ INFO] [1632319618.073904561]: Image #14, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0014.jpg
[ INFO] [1632319618.305228749]: Image #15, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0015.jpg
[ INFO] [1632319618.515402430]: Image #16, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0016.jpg
[ INFO] [1632319618.759004022]: Image #17, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0017.jpg
[ INFO] [1632319618.955550030]: Image #18, image Path: /media/ubuntu/DATA/4slam/OpenREALM/open_data/edm_big_overlap_50p/img_0018.jpg
^C[rviz-7] killing on exit
[realm_mosaicing-6] killing on exit
[realm_ortho_rectification-5] killing on exit
[realm_surface_generation-4] killing on exit
[realm_exiv2_grabber-2] killing on exit
2021-09-22 14:06:59.369 (  13.137s) [        E42E2680] worker_thread_base.cpp:129      0| Thread 'Stage [surface_generation]' received finish request...
2021-09-22 14:06:59.372 (  13.115s) [        2CB75680] worker_thread_base.cpp:129      0| Thread 'Stage [mosaicing]' received finish request...
2021-09-22 14:06:59.372 (  13.115s) [        2CB75680]          mosaicing.cpp:219    ERR| No global map created, skipping saveAll()
2021-09-22 14:06:59.378 (  13.121s) [        CC338680] worker_thread_base.cpp:129      0| Thread 'Stage [ortho_rectification]' received finish request...
2021-09-22 14:06:59.441 (  13.183s) [Stage [ortho_rec] worker_thread_base.cpp:101      0| Thread 'Stage [ortho_rectification]' finished!
2021-09-22 14:06:59.441 (  13.210s) [Stage [surface_g] worker_thread_base.cpp:101      0| Thread 'Stage [surface_generation]' finished!
2021-09-22 14:06:59.441 (  13.184s) [Stage [mosaicing] worker_thread_base.cpp:101      0| Thread 'Stage [mosaicing]' finished!
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by yafenggithub** [comment]
The  orb vocabulary cause this error,I have solved this problem,thanks.I will colse it.

**Comment by laxnpander** [comment]
@yafenggithub Hey, Sorry I didn’t respond quick enough. I was on vacation. Glad you could resolve your issues! I am aware of the problem and thought I patched it already. It is related to the ros bridge not so much repo. But thanks for, pointing it out!

**Comment by zxr12748** [comment]
> The orb vocabulary cause this error,I have solved this problem,thanks.I will colse it.

exactly same problem here,
could you give more detail information about how you solve it? thx~

**Comment by csm-coder** [comment]
@zxr12748 i have the same problem and have no idea about it. do you solve it? thanks.

**Comment by laxnpander** [comment]
@zxr12748 Can you post the terminal output? Or run the pose estimation node in gdb and Post the stacktrace?
http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB

**Comment by laxnpander** [comment]
No updates, so closing until reopened.
