### ISSUE TITLE
why it track failed , and can not create map 

### ISSUE THREAD

**Issue by kintzhao** [laxnpander/OpenREALM#72]
roslaunch realm_ros alexa_noreco.launch   . just track at first, then without  topic: /realm/alexa/pose_estimation/tracked
without CUDA . using the  gived dataset:https://drive.google.com/open?id=1-2h0tasI4wzxZKLBbOz3XbJ7f5xlxlMe

roslaunch realm_ros alexa_gnss.launch  can get the map 

[result.txt](https://github.com/laxnpander/OpenREALM/files/8565413/result.txt)
![Screenshot from 2022-04-27 01-17-07](https://user-images.githubusercontent.com/11779271/165356566-e04cfd8a-8028-4829-85a1-31ee456997fd.png)
![Screenshot from 2022-04-27 01-16-47](https://user-images.githubusercontent.com/11779271/165356565-69b26aa8-9a41-4f36-8249-a49dd90c9e3b.png)
![Screenshot from 2022-04-27 01-16-19](https://user-images.githubusercontent.com/11779271/165356604-4ffaba0d-1bac-4b15-9638-9fd89d57f518.png)

**Comment by laxnpander** [comment]
@kintzhao It's the same as in the other issue you posted. It all comes down to this line:
```c
[2022-04-27 01:08:39.545] [info] initialization succeeded with F
```
and nothing after that. So openvslam seems to freeze after initialization, but I can't tell you why with the given information. Can you try to run it on a desktop computer with Ubuntu 18.04 or 20.04 installed?

**Comment by laxnpander** [comment]
No updates in 20 days, so closing.
