### ISSUE TITLE
Error when run: roslaunch realm_ros alexa_noreco.launch

### ISSUE THREAD

**Issue by wuxiangchao** [laxnpander/OpenREALM#74]
While roslaunch realm_ros alexa_gnss.launch is working whitout any problem, but when i run roslaunch realm_ros alexa_noreco.launch with yaml exception:

[2022-07-20 16:33:55.521] [info] config file loaded: 
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa

=========================== 

sirope@ubuntu20-04:~/SourceCode/OpenREALM/catkin_ws$ roslaunch realm_ros alexa_noreco.launch
... logging to /home/sirope/.ros/log/b0fa8658-0806-11ed-bba5-17ed01860011/roslaunch-ubuntu20-04-40087.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu20-04:35557/

SUMMARY
========

PARAMETERS
 * /realm_exiv2_grabber/config/id: alexa
 * /realm_exiv2_grabber/config/input: //home/sirope/Dat...
 * /realm_exiv2_grabber/config/profile: alexa_noreco
 * /realm_exiv2_grabber/config/rate: 10.0
 * /realm_mosaicing/config/id: alexa
 * /realm_mosaicing/config/profile: alexa_noreco
 * /realm_mosaicing/stage/type: mosaicing
 * /realm_mosaicing/topics/input/frame: /realm/alexa/orth...
 * /realm_ortho_rectification/config/id: alexa
 * /realm_ortho_rectification/config/profile: alexa_noreco
 * /realm_ortho_rectification/stage/type: ortho_rectification
 * /realm_ortho_rectification/topics/input/frame: /realm/alexa/surf...
 * /realm_ortho_rectification/topics/output: /realm/alexa/orth...
 * /realm_pose_estimation/config/id: alexa
 * /realm_pose_estimation/config/method: open_vslam
 * /realm_pose_estimation/config/profile: alexa_noreco
 * /realm_pose_estimation/stage/master: True
 * /realm_pose_estimation/stage/type: pose_estimation
 * /realm_pose_estimation/topics/input/frame: /realm/alexa/input
 * /realm_pose_estimation/topics/output: /realm/alexa/pose...
 * /realm_surface_generation/config/id: alexa
 * /realm_surface_generation/config/profile: alexa_noreco
 * /realm_surface_generation/stage/type: surface_generation
 * /realm_surface_generation/topics/input/frame: /realm/alexa/pose...
 * /realm_surface_generation/topics/output: /realm/alexa/surf...
 * /rosdistro: noetic
 * /rosversion: 1.15.14

NODES
  /
    realm_exiv2_grabber (realm_ros/realm_exiv2_grabber)
    realm_mosaicing (realm_ros/realm_stage_node)
    realm_ortho_rectification (realm_ros/realm_stage_node)
    realm_pose_estimation (realm_ros/realm_stage_node)
    realm_surface_generation (realm_ros/realm_stage_node)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [40110]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b0fa8658-0806-11ed-bba5-17ed01860011
process[rosout-1]: started with pid [40135]
started core service [/rosout]
process[realm_exiv2_grabber-2]: started with pid [40142]
process[realm_pose_estimation-3]: started with pid [40143]
process[realm_surface_generation-4]: started with pid [40144]
process[realm_ortho_rectification-5]: started with pid [40145]
process[realm_mosaicing-6]: started with pid [40146]
process[rviz-7]: started with pid [40147]
[ INFO] [1658306035.516109024]: STAGE_NODE [pose_estimation]: Loading stage settings from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/pose_estimation/stage_settings.yaml
[ INFO] [1658306035.517084211]: STAGE_NODE [pose_estimation]: Detected stage type: 'pose_estimation'
[ INFO] [1658306035.521267874]: STAGE_NODE [pose_estimation]: : Loading camera from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1658306035.521343620]: STAGE_NODE [pose_estimation]: : Detected camera model: 'pinhole'
[ INFO] [1658306035.521355176]: STAGE_NODE [pose_estimation]: : Loading vslam settings from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/pose_estimation/method/open_vslam_settings.yaml
[ INFO] [1658306035.521397945]: STAGE_NODE [pose_estimation]: : Detected vslam type: 'OPEN_VSLAM'
2022-07-20 16:33:55.521 (   0.014s) [        E3910000]    pose_estimation.cpp:40       0| Stage [pose_estimation]: Created Stage with Settings:

	<Param>[save_keyframes]: 0
	<Param>[save_frames]: 0
	<Param>[overlap_max_fallback]: 95
	<Param>[overlap_max]: 100
	<Param>[min_nrof_frames_georef]: 5
	<Param>[init_lost_frames_reset_count]: 15
	<Param>[log_to_file]: 1
	<Param>[use_imu]: 0
	<Param>[save_trajectory_gnss]: 1
	<Param>[queue_size]: 10
	<Param>[path_output]: 
	<Param>[use_vslam]: 1
	<Param>[use_initial_guess]: 0
	<Param>[suppress_outdated_pose_pub]: 0
	<Param>[save_keyframes_full]: 0
	<Param>[save_trajectory_visual]: 1
	<Param>[fallback_strategy]: 1
	<Param>[set_all_frames_keyframes]: 0
	<Param>[update_georef]: 0
	<Param>[th_error_georef]: 1
	<Param>[type]: pose_estimation
	<Param>[do_delay_keyframes]: 1
[2022-07-20 16:33:55.521] [info] config file loaded: 
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
[ INFO] [1658306035.522831585]: Exiv2 Grabber Node [Ankommen]: Successfully loaded camera: 
	cx = 610.324
	cy = 516.917
	fx = 1209.07
	fy = 1210.66
	k1 = -0.198806
	k2 = 0.122544
	p1 = -0.000221
	p2 = -0.000877
[ INFO] [1658306035.523947401]: STAGE_NODE [surface_generation]: Loading stage settings from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/surface_generation/stage_settings.yaml
[ INFO] [1658306035.524781407]: STAGE_NODE [surface_generation]: Detected stage type: 'surface_generation'
[ INFO] [1658306035.527604429]: Scanning input image for provided meta tags...
[ INFO] [1658306035.527887622]: [FOUND]		'Exif.GPSInfo.GPSAltitude'
[ INFO] [1658306035.527899782]: [FOUND]		'Exif.GPSInfo.GPSLatitude'
[ INFO] [1658306035.527905394]: [FOUND]		'Exif.GPSInfo.GPSLatitudeRef'
[ INFO] [1658306035.527910575]: [FOUND]		'Exif.GPSInfo.GPSLongitude'
[ INFO] [1658306035.527917302]: [FOUND]		'Exif.GPSInfo.GPSLongitudeRef'
[ INFO] [1658306035.527922438]: [FOUND]		'Exif.Image.Model'
[ INFO] [1658306035.527927906]: [FOUND]		'Xmp.exif.REALM.Heading'
[ WARN] [1658306035.527934613]: [NOT FOUND]	'Xmp.exif.REALM.Timestamp'
[ INFO] [1658306035.527955755]: Image #0, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0000.jpg
[ INFO] [1658306035.528631134]: STAGE_NODE [ortho_rectification]: Loading stage settings from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/ortho_rectification/stage_settings.yaml
[ INFO] [1658306035.529603235]: STAGE_NODE [ortho_rectification]: Detected stage type: 'ortho_rectification'
[ INFO] [1658306035.530318175]: STAGE_NODE [surface_generation]: : Loading camera from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1658306035.530424005]: STAGE_NODE [surface_generation]: : Detected camera model: 'pinhole'
[ INFO] [1658306035.532232039]: STAGE_NODE [surface_generation]: Started stage node successfully!
2022-07-20 16:33:55.532 (   0.020s) [Stage [surface_g] worker_thread_base.cpp:43       0| Thread 'Stage [surface_generation]' starting loop...
[ INFO] [1658306035.535227070]: STAGE_NODE [ortho_rectification]: : Loading camera from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1658306035.535305601]: STAGE_NODE [ortho_rectification]: : Detected camera model: 'pinhole'
Stage [ortho_rectification]: Created Stage with Settings: 
	<Param>[save_elevation_angle]: 0
	<Param>[save_ortho_rgb]: 0
	<Param>[save_valid]: 0
	<Param>[publish_pointcloud]: 0
	<Param>[GSD]: 0.1
	<Param>[save_elevation]: 0
	<Param>[path_output]: 
	<Param>[save_ortho_gtiff]: 0
	<Param>[queue_size]: 5
	<Param>[log_to_file]: 1
	<Param>[type]: ortho_rectification
[ INFO] [1658306035.536201332]: STAGE_NODE [ortho_rectification]: Started stage node successfully!
2022-07-20 16:33:55.536 (   0.019s) [Stage [ortho_rec] worker_thread_base.cpp:43       0| Thread 'Stage [ortho_rectification]' starting loop...
[ INFO] [1658306035.536630296]: STAGE_NODE [mosaicing]: Loading stage settings from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/mosaicing/stage_settings.yaml
[ INFO] [1658306035.537092126]: STAGE_NODE [mosaicing]: Detected stage type: 'mosaicing'
[ INFO] [1658306035.540167187]: STAGE_NODE [mosaicing]: : Loading camera from path:
	/home/sirope/SourceCode/OpenREALM/catkin_ws/src/OpenREALM_ROS1_Bridge/realm_ros/profiles/alexa_noreco/camera/calib.yaml
[ INFO] [1658306035.540243116]: STAGE_NODE [mosaicing]: : Detected camera model: 'pinhole'
Stage [mosaicing]: Created Stage with Settings: 
	<Param>[save_num_obs_one]: 1
	<Param>[save_elevation_obs_angle_all]: 0
	<Param>[save_elevation_obs_angle_one]: 1
	<Param>[save_elevation_var_one]: 0
	<Param>[save_elevation_one]: 1
	<Param>[save_ortho_gtiff_all]: 0
	<Param>[save_dense_ply]: 1
	<Param>[save_num_obs_all]: 0
	<Param>[save_ortho_gtiff_one]: 1
	<Param>[type]: mosaicing
	<Param>[log_to_file]: 1
	<Param>[queue_size]: 5
	<Param>[downsample_publish_mesh]: 0.5
	<Param>[th_elevation_min_nobs]: 2
	<Param>[save_elevation_var_all]: 0
	<Param>[th_elevation_variance]: 1
	<Param>[path_output]: 
	<Param>[save_elevation_mesh_one]: 0
	<Param>[publish_mesh_every_nth_kf]: 0
	<Param>[publish_mesh_at_finish]: 1
	<Param>[split_gtiff_channels]: 0
	<Param>[save_elevation_all]: 0
	<Param>[save_ortho_rgb_one]: 1
	<Param>[save_valid]: 0
	<Param>[save_ortho_rgb_all]: 0
[ INFO] [1658306035.541235747]: STAGE_NODE [mosaicing]: Started stage node successfully!
2022-07-20 16:33:55.541 (   0.015s) [Stage [mosaicing] worker_thread_base.cpp:43       0| Thread 'Stage [mosaicing]' starting loop...
[ INFO] [1658306035.628187859]: Image #1, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0001.jpg
[realm_pose_estimation-3] process has died [pid 40143, exit code -6, cmd /home/sirope/SourceCode/OpenREALM/catkin_ws/devel/lib/realm_ros/realm_stage_node __name:=realm_pose_estimation __log:=/home/sirope/.ros/log/b0fa8658-0806-11ed-bba5-17ed01860011/realm_pose_estimation-3.log].
log file: /home/sirope/.ros/log/b0fa8658-0806-11ed-bba5-17ed01860011/realm_pose_estimation-3*.log
[ INFO] [1658306035.728340007]: Image #2, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0002.jpg
[ INFO] [1658306035.828527950]: Image #3, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0003.jpg
[ INFO] [1658306035.928716375]: Image #4, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0004.jpg
[ INFO] [1658306036.028871192]: Image #5, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0005.jpg
[ INFO] [1658306036.129023137]: Image #6, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0006.jpg
[ INFO] [1658306036.229386737]: Image #7, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0007.jpg
[ INFO] [1658306036.329641969]: Image #8, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0008.jpg
[ INFO] [1658306036.430049655]: Image #9, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0009.jpg
[ INFO] [1658306036.530511937]: Image #10, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0010.jpg
[ INFO] [1658306036.633916219]: Image #11, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0011.jpg
[ INFO] [1658306036.734167205]: Image #12, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0012.jpg
[ INFO] [1658306036.834381002]: Image #13, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0013.jpg
[ INFO] [1658306036.934637609]: Image #14, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0014.jpg
[ INFO] [1658306037.034951447]: Image #15, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0015.jpg
[ INFO] [1658306037.135181163]: Image #16, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0016.jpg
[ INFO] [1658306037.236101033]: Image #17, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0017.jpg
[ INFO] [1658306037.336470873]: Image #18, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0018.jpg
[ INFO] [1658306037.436694378]: Image #19, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0019.jpg
[ INFO] [1658306037.536952899]: Image #20, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0020.jpg
[ INFO] [1658306037.637237622]: Image #21, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0021.jpg
[ INFO] [1658306037.737528990]: Image #22, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0022.jpg
[ INFO] [1658306037.837735791]: Image #23, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0023.jpg
[ INFO] [1658306037.938020038]: Image #24, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0024.jpg
[ INFO] [1658306038.043601440]: Image #25, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0025.jpg
[ INFO] [1658306038.143881330]: Image #26, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0026.jpg
[ INFO] [1658306038.244076294]: Image #27, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0027.jpg
[ INFO] [1658306038.344323147]: Image #28, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0028.jpg
[ INFO] [1658306038.444758482]: Image #29, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0029.jpg
[ INFO] [1658306038.544998161]: Image #30, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0030.jpg
[ INFO] [1658306038.645533250]: Image #31, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0031.jpg
[ INFO] [1658306038.745676843]: Image #32, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0032.jpg
[ INFO] [1658306038.845953287]: Image #33, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0033.jpg
[ INFO] [1658306038.946444969]: Image #34, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0034.jpg
[ INFO] [1658306039.046825003]: Image #35, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0035.jpg
[ INFO] [1658306039.147366247]: Image #36, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0036.jpg
[ INFO] [1658306039.247837382]: Image #37, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0037.jpg
[ INFO] [1658306039.348962415]: Image #38, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0038.jpg
[ INFO] [1658306039.449809985]: Image #39, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0039.jpg
[ INFO] [1658306039.550191706]: Image #40, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0040.jpg
[ INFO] [1658306039.650699972]: Image #41, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0041.jpg
[ INFO] [1658306039.751108932]: Image #42, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0042.jpg
[ INFO] [1658306039.851400824]: Image #43, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0043.jpg
[ INFO] [1658306039.951703346]: Image #44, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0044.jpg
[ INFO] [1658306040.052935162]: Image #45, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0045.jpg
[ INFO] [1658306040.153778543]: Image #46, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0046.jpg
^C[rviz-7] killing on exit
[realm_mosaicing-6] killing on exit
[ INFO] [1658306040.254277434]: Image #47, image Path: //home/sirope/Datasets/open_realm_edm_dataset/edm_big_overlap_50p/img_0047.jpg
[realm_ortho_rectification-5] killing on exit
[realm_surface_generation-4] killing on exit
[realm_exiv2_grabber-2] killing on exit
2022-07-20 16:34:00.402 (   4.890s) [         2087000] worker_thread_base.cpp:129      0| Thread 'Stage [surface_generation]' received finish request...
^C2022-07-20 16:34:00.441 (   4.930s) [Stage [surface_g] worker_thread_base.cpp:101      0| Thread 'Stage [surface_generation]' finished!
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
2022-07-20 16:34:00.531 (   5.005s) [        C41E2000] worker_thread_base.cpp:129      0| Thread 'Stage [mosaicing]' received finish request...

**Comment by Ahmad-Drak** [comment]
This might be related to the grid_map? maybe this helps
https://github.com/ANYbotics/grid_map#iterators

**Comment by wuxiangchao** [comment]
> This might be related to the grid_map? maybe this helps https://github.com/ANYbotics/grid_map#iterators

Thanks, let me try.

**Comment by laxnpander** [comment]
@wuxiangchao Hey, did you find a solution to your problem? First of all the error indicates it is related to the yaml parser. Here I use opencv, so this is not related to OpenREALM directly. What happens very often is that ROS and OpenREALM link to different versions of opencv. Please make sure both use the same version. This can be tricky sometimes as cmake can be a pain in this regard. What works best is having only the ros opencv version. So remove all custom opencv installs from your computer.

**Comment by laxnpander** [comment]
@wuxiangchao Reopen if problem persists.
