### ISSUE TITLE
Heading

### ISSUE THREAD

**Issue by dairejpwalsh** [laxnpander/OpenREALM#8]
Hi, How can I change the heading meta tag in the XMP of an image. Do I need to use exiv2. I tried with exiftools but I just get tag doesn't exist.

**Comment by ykhedar** [comment]
Please provide more Info. 
1. Which launch file are you using to run the mapping?
2. Which camera images do you use?

Normally while using the exiv_grabber for the mapping pipeline you would change the exif tags in the config [file](realm_ros/profiles/alexa_gnss/config/exif.yaml) according to the exif tags found in the image of your camera.

**Comment by laxnpander** [comment]
Reopen an issue if you still have problems.
