### ISSUE TITLE
Question about Vslam

### ISSUE THREAD

**Issue by fulizi123** [laxnpander/OpenREALM#80]
I know Vslam need camera intrinsics to run. How does OPENrealm get camera parameters from the image stream ?

**Comment by zhangjd1029** [comment]
> 
Hello, classmates, I am also running this open source project recently. Could you please add wechat for communication

**Comment by fulizi123** [comment]
Sure, it's my pleasure. My wechat is 'c442022734'.

**Comment by laxnpander** [comment]
@fulizi123 Hey all, assuming you are using the OpenREALM ROS1 Bridge (https://github.com/laxnpander/OpenREALM_ROS1_Bridge) there are several parameter files to adjust for custom datasets. You will find example profiles in this directory: https://github.com/laxnpander/OpenREALM_ROS1_Bridge/tree/master/realm_ros/profiles

A profile is a set of configurations for a specific camera + processing hardware. Camera calibration is handled here https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/master/realm_ros/profiles/alexa_reco/camera/calib.yaml 

Please note, that processing your own dataset comes with a learning curve. The default values might not work good for you depending on the resolution of your images, your frame rate, your flight altitude, scene, etc.

**Comment by fulizi123** [comment]
@laxnpander OK，I know. Thank you very much.
