### ISSUE TITLE
Error running alexa_reco.launch

### ISSUE THREAD

**Issue by zhangjd1029** [laxnpander/OpenREALM#81]

**Comment by zhangjd1029** [comment]
Hello, I have solved this problem. It is really the problem of cuda's insufficient computing power.
Now run alexa_ After reco.launch, its output folder contains only identification and ortho_ rectification，pose_ estimation，surface_ Generation, there is no mosaicing folder. Is this normal.
In addition, how do you determine whether it is a 2.5d map
I would appreciate it if you could reply

**Comment by zhangjd1029** [comment]
![1](https://user-images.githubusercontent.com/117131706/219660787-97e392bc-47e1-4133-897e-338883c426f4.png)

**Comment by zhangjd1029** [comment]
Hello, thank you for always maintaining the OpenRealm framework. I managed to run gnss, noreco and reco in RVIZ, and here are the results
![1](https://user-images.githubusercontent.com/117131706/219662051-3ff316f7-0925-432b-917a-0eb0dd83f2df.png)
![2](https://user-images.githubusercontent.com/117131706/219662082-bc4fbf40-a02c-482e-b72b-ef70b94f76c9.png)
![3](https://user-images.githubusercontent.com/117131706/219662106-eb356d06-ae02-4e9e-8f32-6a06b0b81804.png)
I saw in the paper that running reco should be a 2.5D elevation map, but in the results I ran, it is not stereoscopic, so I would like to ask you if these are the correct results?If the result is correct, then where does it manifest its three-dimensionality?
Looking forward to your reply! Thank you very much!

**Comment by laxnpander** [comment]
@zhangjd1029 Looks okay, publishing a 3d mesh is disabled currently because it was bugging too much. You will find 2.5D information (e.g. geotiff) in the realm_ros/output folder. You can also enable PLY export at the end by setting this flag to 1:
https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/65a86d465b5ba0b5256f5c8f1bb8090ec3a027f8/realm_ros/profiles/alexa_reco/mosaicing/stage_settings.yaml#L37

**Comment by zhangjd1029** [comment]
Thank you very much for your response!
I didn't find geotiff in the output folder, should it be in the output/timestamp/mosaicing folder?
I set the parameter to 1, when running the launch file, I added the pointcloud2 plugin, but I can't see the point cloud, is this way to view the point cloud correct? If not, how can I check it?
When I run GNSS and Noreco, there will be a mosaicing folder in the output folder, but when I run Reco, there will be no such folder, is this normal?
There are a lot of questions, please give them in your spare time.
Thanks again for your reply!

**Comment by laxnpander** [comment]
@zhangjd1029 Ah Sorry, it’s a bug. You can specify the output directory for every node individually, but you don’t have to. For the alexa_reco it seems like I pushed a custom change. Look at the launch file and comment this line or put a directory of your choice:

https://github.com/laxnpander/OpenREALM_ROS1_Bridge/blob/65a86d465b5ba0b5256f5c8f1bb8090ec3a027f8/realm_ros/launch/alexa_reco.launch#L71

**Comment by zhangjd1029** [comment]
Thank you very much for your answer!
I managed to find the mosaicing folder. I assume the point cloud files are in the mosaicing/elevation/ply folders? However, after I run it for many times, files are generated in color_map and gtiff folder, while nothing is found in ply folder. May I ask if I did not set anything correctly? Or is the point cloud file not here?
Thank you again and look forward to your reply.

**Comment by laxnpander** [comment]
@zhangjd1029 Jeah, should be. Does it close without an error? Hard to diagnose from a distance without any error message or indication of what's going wrong. Setting the flag should be enough. But I know it's also one of the lesser used features.

**Comment by laxnpander** [comment]
Reopen if questions persist.
