### ISSUE TITLE
Error running alexa_noreco.launch

### ISSUE THREAD

**Issue by tongtongliu0809** [laxnpander/OpenREALM#82]
Hello, thank you for always maintaining the OpenRealm framework.When running roslaunch realm_ros alexa_noreco.launch on dataset edm_big_overlap_50p using default profiles, I didn't see any ouput in the Rviz window.
![2023-03-21 14-47-01屏幕截图](https://user-images.githubusercontent.com/128456146/226535741-79b21658-1a0d-4240-aafd-d01fe7778469.png)
![2023-03-21 14-47-44屏幕截图](https://user-images.githubusercontent.com/128456146/226535761-b2c3bdcf-a4e2-40a3-a2ad-ebbaaf5d12ba.png)
Looking forward to your reply! Thank you very much!

**Comment by laxnpander** [comment]
@tongtongliu0809 Hey, the missing rviz plugin is fine. You can clone it to your catkin_ws from here, but it is not mandatory: https://github.com/laxnpander/rviz_satellite 

The wrong path is a problem though. You should find the vocabulary here: https://github.com/laxnpander/OpenREALM_ROS1_Bridge/tree/master/realm_ros/profiles/alexa_noreco/pose_estimation/method/open_vslam 

Do you have any other info on what might go wrong?

**Comment by laxnpander** [comment]
Reopen if issues persist.

**Comment by dubing-bit** [comment]
hello,thank you your work! i had a similar error.
![image](https://github.com/laxnpander/OpenREALM/assets/67738467/8142e4c0-6b05-4d9f-b14f-9166b2e6329e) 
I had clone the https://github.com/laxnpander/rviz_satellite to the "catkin_ws" directory,but the problem still exists, I'm a newbie and can't solve it.
