### ISSUE TITLE
How to use GPU stereo reconstruction to obtain 2.5D elevation map

### ISSUE THREAD

**Issue by tongtongliu0809** [laxnpander/OpenREALM#84]
Hello, thank you for always maintaining the OpenRealm framework.We've run out the first three modes. How can the fourth mode be realized, i.e., 2.5D elevation maps based on lat, lon, alt and visual SLAM pose estimation using GPU stereo reconstruction?
Looking forward to your reply! Thank you very much!

**Comment by laxnpander** [comment]
@tongtongliu0809 The sparse cloud reconstruction is currently not enabled anymore. So it is very likely you were already using gpu stereo reconstruction and 2.5D elevation maps when you ran alexa_reco.launch. Note, that resolution is rather bad (not comparable to traditional photogrammetry) and quality can also be improved. But elevation information is used based on reprojection from grid.

**Comment by laxnpander** [comment]
Reopen if necessary.
