### ISSUE TITLE
algorithm about SurfaceGeneration

### ISSUE THREAD

**Issue by tsingjinyun** [laxnpander/OpenREALM#88]
https://github.com/laxnpander/OpenREALM/blob/master/modules/realm_core/src/camera.cpp#L348 
    cv::Mat u = (cv::Mat_<double>(3, 1) << img_bounds.at<double>(i, 0), img_bounds.at<double>(i, 1), 1.0);
    double s = (pt - m_t).dot(n) / (m_R * m_K.inv() * u).dot(n);
    cv::Mat p = m_R * (s * m_K.inv() * u) + m_t;
here code use algorithm，has any reference paper?

**Comment by laxnpander** [comment]
Hmm, not really and can't remember. The second line should be the algebraic form of line -> plane intersection:
https://en.wikipedia.org/wiki/Line%E2%80%93plane_intersection
The third line is a inverse pinhole projection:
https://towardsdatascience.com/inverse-projection-transformation-c866ccedef1c

**Comment by tsingjinyun** [comment]
thank you, and great project
