### ISSUE TITLE
roslaunch realm_ros failed

### ISSUE THREAD

**Issue by ChoiiYill** [laxnpander/OpenREALM#95]
Hello, 
when I try : **roslaunch realm_ros alexa_noreco.launch**
And I encounter with this：
RLException: [alexa_noreco.launch] is neither a launch file in package [realm_ros] nor is [realm_ros] a launch file name
The traceback for the exception was written to the log file
**How to fix this? Thanks.**

**Comment by ChoiiYill** [comment]
> Hello, when I try : **roslaunch realm_ros alexa_noreco.launch** And I encounter with this： RLException: [alexa_noreco.launch] is neither a launch file in package [realm_ros] nor is [realm_ros] a launch file name The traceback for the exception was written to the log file **How to fix this? Thanks.**

Sorry, I am a fledgling of ROS develop.
I have solved this problem by setting environment variables. 
1. Open bashrc by: **sudo vim ~/.bashrc**
Add this two lines to the end:
_source /home/pc/app/OpenREALM/catkin_ws/devel/setup.sh
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/home/pc/app/OpenREALM/catkin_ws/_
2. Save and restart bashrc: **source ~/.bashrc**

**Comment by hfwuyanzu666** [comment]
Do you have the following errors when running nocore.launch and core.launch?
[realm_pose_estimation-3] process has died [pid 16691, exit code -11,  cmd /home/yanzu/openrealm/openrealm_ros_bridge/catkin_ws/devel/lib/realm_ros/realm_stage_node  __name:=realm_pose_estimation  __log:=/home/yanzu/.ros/log/8156f674-86f0-11ee-b3fc-d6499dadd82b/realm_pose_estimation-3.log].
log file: /home/yanzu/.ros/log/8156f674-86f0-11ee-b3fc-d6499dadd82b/realm_pose_estimation-3*.log

I didn't know how to solve it. I tried similar problems and solutions that other people had come up with before and it didn't work. I would appreciate it if you know how to solve it

**Comment by ChoiiYill** [comment]
> Do you have the following errors when running nocore.launch and core.launch? [realm_pose_estimation-3] process has died [pid 16691, exit code -11, cmd /home/yanzu/openrealm/openrealm_ros_bridge/catkin_ws/devel/lib/realm_ros/realm_stage_node __name:=realm_pose_estimation __log:=/home/yanzu/.ros/log/8156f674-86f0-11ee-b3fc-d6499dadd82b/realm_pose_estimation-3.log]. log file: /home/yanzu/.ros/log/8156f674-86f0-11ee-b3fc-d6499dadd82b/realm_pose_estimation-3*.log
> 
> I didn't know how to solve it. I tried similar problems and solutions that other people had come up with before and it didn't work. I would appreciate it if you know how to solve it

Yes, I've met this problem when I use Ubuntu20.04, OpenCV-4. I solve it by using Ubuntu18.04 and OpenCV-3.4.
I think it might cause by **cv_bridge**, which you can refer to this issue. (issue #22 )

**Comment by hfwuyanzu666** [comment]
Thank you very much for your valuable answer. I went to deal with other things in the middle of the project, which delayed the project for a while. I tried to match the cv_bridge version with the opencv version, and the running result was still the same as before. The [realm_pose_estimation-3] process has died [pid 10931, exit code 1] error still occurs.
I let it run all the way down to the state in the image below and nothing else changed
![3faa680029b393d17012c0039954470f](https://github.com/laxnpander/OpenREALM/assets/105181434/3badc161-b593-4c0f-97ad-b7a3798db580)

**Comment by hfwuyanzu666** [comment]
The following is where the program is reporting errors
![2023-12-05 23-35-47 的屏幕截图](https://github.com/laxnpander/OpenREALM/assets/105181434/26efc57b-05cf-44a0-a997-582bef52fda2)

**Comment by hfwuyanzu666** [comment]
> > 运行nocore.launch和core.launch时是否出现以下错误？[realm_pose_estimation-3]进程已死亡[pid 16691，退出代码-11，cmd /home/yanzu/openrealm/openrealm_ros_bridge/catkin_ws/devel/lib/realm_ros/realm_stage_node __name:=realm_pose_estimation __log:=/home/yanzu/.ros /log/8156f674-86f0-11ee-b3fc-d6499dadd82b/realm_pose_estimation-3.log]。日志文件：/home/yanzu/.ros/log/8156f674-86f0 -11ee-b3fc-d6499dadd82b/realm_pose_estimation-3*.log
> > 我不知道如何解决。我尝试了其他人之前提出的类似问题和解决方案，但没有成功。如果您知道如何解决它，我将不胜感激
> 
> 是的，我在使用Ubuntu20.04、OpenCV-4时也遇到过这个问题。我使用Ubuntu18.04和OpenCV-3.4解决了这个问题。 我认为可能是**cv_bridge**引起的，你可以参考这个问题。（问题[＃22](https://github.com/laxnpander/OpenREALM/issues/22)）

If convenient, could you add a contact information? I still have some questions to ask you about this open source project. My wechat is 13865974859.Thanks very much.

**Comment by ChoiiYill** [comment]
> > > 运行nocore.launch和core.launch时是否出现以下错误？[realm_pose_estimation-3]进程已死亡[pid 16691，退出代码-11，cmd /home/yanzu/openrealm/openrealm_ros_bridge/catkin_ws/devel/lib/realm_ros/realm_stage_node __name:=realm_pose_estimation __log:=/home/yanzu/.ros /log/8156f674-86f0-11ee-b3fc-d6499dadd82b/realm_pose_estimation-3.log]。日志文件：/home/yanzu/.ros/log/8156f674-86f0 -11ee-b3fc-d6499dadd82b/realm_pose_estimation-3*.log
> > > 我不知道如何解决。我尝试了其他人之前提出的类似问题和解决方案，但没有成功。如果您知道如何解决它，我将不胜感激
> > 
> > 
> > 是的，我在使用Ubuntu20.04、OpenCV-4时也遇到过这个问题。我使用Ubuntu18.04和OpenCV-3.4解决了这个问题。 我认为可能是**cv_bridge**引起的，你可以参考这个问题。（问题[＃22](https://github.com/laxnpander/OpenREALM/issues/22)）
> 
> If convenient, could you add a contact information? I still have some questions to ask you about this open source project. My wechat is 13865974859.Thanks very much.

I have not encountered such a problem, sry.
