### ISSUE TITLE
My own dataset

### ISSUE THREAD

**Issue by zhangjd1029** [laxnpander/OpenREALM#97]
Thank you very much for your work.

Does OpenRealm have to run data with GPS information? I have some unmanned aerial vehicle high-altitude images taken by myself, but they do not contain GPS information. Can they be operated?

If GPS data is necessary, can the code be modified to run without relying on GPS data?

Looking forward to your reply。

**Comment by laxnpander** [comment]
I don't think it can. GNSS is used to estimate the scale and properly project the images. It could work in theory, but practically the pipeline is not designed around such a case. Are you sure your images have no GNSS meta tags? Usually they are hidden in the jpegs. DJI for example shouldn't be an issue to process.

**Comment by zhangjd1029** [comment]
Thank you for your reply.
My image was not captured by a DJI equipped camera, so there is no GPS data in the photo data taken. I have been trying to run this image on my own after running OpenRealm for the past two days, but I still have problems. So openrealm cannot run the dataset I collected.

**Comment by laxnpander** [comment]
Without further information there is nothing I can help with here.
